destinations = ['Alaska', 'Montana', 'Taiwan', 'Norway', 'Ireland']
print(destinations)
print(sorted(destinations))
print(destinations)
print(sorted(destinations, reverse=True))
print(destinations)
destinations.reverse()
print(destinations)
destinations.reverse()
print(destinations)
destinations.sort()
print(destinations)
destinations.sort(reverse=True)
print(destinations)
#page 46 homework
